version: "2"

services:

  web_marketing:
    image: vbosstech/mautic
    container_name: web_marketing
    depends_on:
      - database_marketing
    ports:
      - "80:80"
    volumes:
      - volume_web_marketing:/var/www/html
      # - $PWD/custom:/var/www/html
    environment:
      MAUTIC_DB_HOST: database_marketing
      MAUTIC_DB_NAME: marketing
      MAUTIC_DB_USER: marketing
      MAUTIC_DB_PASSWORD: Job4U.io
      MAUTIC_TRUSTED_PROXIES: 0.0.0.0/0

  database_marketing:
    image: mysql:5.6
    container_name: database_marketing
    ports:
      - 3306:3306
    volumes:
      - volume_database_marketing:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: MysqlRootPassword
      MYSQL_DATABASE: marketing
      MYSQL_USER: marketing
      MYSQL_PASSWORD: Job4U.io

  nginx:
    image: nginx
    container_name: nginx_marketing
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - volume_nginx_sslcerts:/etc/ssl/private
    depends_on:
      - web_marketing
    entrypoint:
      - "bash"
      - "-c"
    command: |
      "if [ ! -f /etc/ssl/private/marketing.crt ]; then
        echo 'ssl certificate missing, installing openssl to create a new one'
        apt-get update && apt-get install openssl -y
        openssl req -x509 -newkey rsa:2048 -sha256 -nodes -keyout /etc/ssl/private/marketing.key -out /etc/ssl/private/marketing.crt -subj '/CN=marketing.local' -days 3650
        echo 'Created new ssl certificate'
      fi
      exec nginx -g 'daemon off;'"

volumes:
  volume_web_marketing:
  volume_database_marketing:  
  volume_nginx_sslcerts: